version: '3'

services:

  mongo:
    image: "mongo"
    container_name: mongo
    ports:
      - "27017:27017"

  todo-app-api:
    build: ./todo-app-api
    container_name: todo-app-api
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  todo-app-ui:
    build: ./todo-app-ui
    container_name: todo-app-ui
    ports:
      - "3001:3001"
